title: Yachao Zhu
description: PhD Student in Computer Science at University of Leeds
url: "https://edumoot.github.io"
baseurl: ""

# Build settings
markdown: kramdown
include: ['_pages']

# Author information
author:
  name: Yachao Zhu
  email: scyzhu@leeds.ac.uk
  github: edumoot
  linkedin: zhuyachao@yahoo.com

# Navigation
nav_pages:
  - title: About
    url: /
  - title: CV
    url: /cv/