title: Yachao Zhu
description: PhD Student in Computer Science at University of Leeds
url: "https://edumoot.github.io"
baseurl: ""

markdown: kramdown
include: ['_pages']

author:
  name: Yachao Zhu
  email: scyzhu@leeds.ac.uk
  github: edumoot
  linkedin: yachao-zhu-513a38a5

nav_pages:
  - title: About
    url: /
  - title: CV
    url: /cv/